### ISSUE TITLE
Can`t build - status is not pending in complete stage

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#130]
Hello,

With a successfull build i get :

```bash
Checked 601 files in 3 seconds
No syntax error found
PLUGIN: SUCCESS

RUNNING PLUGIN: PHP Docblock Checker (Stage: Test)
PLUGIN: FAILED (ALLOWED)

RUNNING PLUGIN: Technical Debt (Stage: Test)
Found 14 instances of TODO, FIXME, TO DO, FIX ME
PLUGIN: FAILED (ALLOWED)

RUNNING PLUGIN: SensioLabs Security Checker (Stage: Test)
PLUGIN: SUCCESS

BUILD SUCCESS

RUNNING PLUGIN: MySQL (Stage: Complete)
PLUGIN: SUCCESS

RUNNING PLUGIN: Email (Stage: Complete)
1 emails sent.
0 emails failed to send.
PLUGIN: SUCCESS

Removing Build.
Can`t build - status is not pending
````

when i look in the log i get :!

```bash
2017-10-30 14:50:47,156 INFO success: phpcensor_00 entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Oct 30 14:50:37 coreos_production_49 rkt[8135]: [260944.886831] apache-phpcensor[11]: 2017-10-30 14:50:37,146 INFO spawned: 'phpcensor_00' with pid 15322
2017-10-30 14:50:36,112 INFO exited: phpcensor_00 (exit status 255; not expected)
  thrown in /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php on line 127
#3 {main}
#2 [internal function]: PHPCensor\Store\BuildErrorWriter->__destruct()
#1 /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php(41): PHPCensor\Store\BuildErrorWriter->flush()
#0 /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php(127): PDOStatement->execute(Array)
Stack trace:
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_date' in 'field list' in /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php:127

[1B blob data]
  thrown in /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php on line 127
#3 {main}
#2 [internal function]: PHPCensor\Store\BuildErrorWriter->__destruct()
#1 /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php(41): PHPCensor\Store\BuildErrorWriter->flush()
#0 /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php(127): PDOStatement->execute(Array)
Stack trace:
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_date' in 'field list' in /data/htdocs/phpcensor/src/PHPCensor/Store/BuildErrorWriter.php:127

```
I was thinking of a migration error :
![image](https://user-images.githubusercontent.com/1699839/32177805-77ee99be-bd8b-11e7-8387-cbf6e4497e0d.png)

no success ... 

Structure of "build_error" table :

![image](https://user-images.githubusercontent.com/1699839/32177922-bc0e60ac-bd8b-11e7-89eb-9675a1856f71.png)

how to fix it, a migration have been skipped ?

**Comment by corpsee** [comment]
Hello @vinpel! Thank you for the issue.
It is my fault and now I fixed it. Can you check fresh `master` branch?
