### ISSUE TITLE
phpcensor.project_group missing

### ISSUE THREAD

**Issue by niemiha** [php-censor/php-censor#161]
## Expected behavior

Getting the php-censor up :P

## Actual behavior

I tried to install the php-censor but in the end of the installing script (interactive) after giving the user data there was an database error. Sorry, somehow I managed to lose the actual error message (out of frustration). So I tried to add the user manually. Of course getting the hash was impossible but I just thought that password forgotten would cure it. And yes, I got the pasword change page. But after giving the new password the server gave error 500. From the error log I found the culprit:

[05-Mar-2018 11:25:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'phpcensor.project_group' doesn't exist' in /srv/php-censor/php-censor.local/src/B8Framework/Store.php:211
> Stack trace:
> #0 /srv/php-censor/php-censor.local/src/B8Framework/Store.php(211): PDOStatement->execute(Array)
> #1 /srv/php-censor/php-censor.local/src/PHPCensor/Application.php(132): b8\Store->getWhere(Array, 100, 0, Array, Array)
> #2 /srv/php-censor/php-censor.local/src/PHPCensor/Application.php(96): PHPCensor\Application->setLayoutVariables(Object(PHPCensor\View))
> #3 /srv/php-censor/php-censor.local/public/index.php(8): PHPCensor\Application->handleRequest()
> #4 {main}
>   thrown in /srv/php-censor/php-censor.local/src/B8Framework/Store.php on line 211

## Steps to reproduce

Should appear from Actual behavior...

## Environment

*CENTO5, PHP 5.6, MariaDB 5.5.52*

**Comment by corpsee** [comment]
@niemiha Looks like migrations failed on installation process for some reasons. I couldn't reproduce the problem on my MariaDB :(

1. Can you give version of PHP Censor what you install (fresh `master` branch or tag version)?
2. Can you try to do new clean installation of PHP Censor and give first error from installation process?

Thanks!

**Comment by niemiha** [comment]
I tried now with gzipper tarball: php-censor-v0.21.0

After trying to generate admin and giving the password the following error message appears:

PHP Censor failed to create your admin account!
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'provider_key' in 'field list'
PHP Censor failed to create default project group!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'phpcensor.project_group' doesn't exist

I have a strong feeling that the database is not created OK

The following tables have been generated:

+---------------------+
| Tables_in_phpcensor |
+---------------------+
| build               |
| build_meta          |
| migration           |
| project             |
| user                |
+---------------------+
5 rows in set (0.00 sec)

**Comment by corpsee** [comment]
@niemiha Can you give full installation console output please?

**Comment by corpsee** [comment]
Are you install on empty DB without tables?

**Comment by niemiha** [comment]
Sorry, I can give full installation console output only tomorrow, left already for today.

And yes, the database was just created empty database,

**Comment by niemiha** [comment]
Sorry for delay.

Yes, the database was just newly created new database.

The full installation input-output is as follows:


***************************************
*  Welcome to PHP Censor installation *
***************************************

Checking requirements...

OK

Please answer the following questions:
--------------------------------------

Please enter your database type (mysql or pgsql): mysql
Please enter your database host (default: localhost):
Please enter your database port (default: empty):
Please enter your database name (default: php-censor-db): phpcensor
Please enter your DB user (default: php-censor-user): phpcensor
Please enter your database password:

Your PHP Censor URL ("http://php-censor.local" for example): http://php-censor.ccc.dd
Use beanstalkd to manage build queue? n
Skipping beanstalkd configuration.
Setting up your database...
In Environment.php line 134:

  Warning: date(): It is not safe to rely on the system's timezone settings.
  You are *required* to use the date.timezone setting or the date_default_tim
  ezone_set() function. In case you used any of those methods and you are sti
  ll getting this warning, you most likely misspelled the timezone identifier
  . We selected the timezone 'UTC' for now, but please set date.timezone to s
  elect your timezone. in /srv/phpcensor/php-censor-v0.21.0/vendor/robmorgan/
  phinx/src/Phinx/Migration/Manager/Environment.php line 134


php-censor-migrations:migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE]


using migration paths
 - /srv/phpcensor/php-censor-v0.21.0/src/PHPCensor/Migrations
warning no environment specified, defaulting to: php-censor
using adapter mysql
using database phpcensor

 == 20140513143726 InitialMigration: migrating

OK
Admin email: aaaa.bbbbb@ccc.dd
Admin name: admin
Admin password:
PHP Censor failed to create your admin account!
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'provider_key' in 'field list'
PHP Censor failed to create default project group!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'phpcensor.project_group' doesn't exist

**Comment by corpsee** [comment]
Thank you, @niemiha for the details! You should to set `date.timezone` setting in your `php.ini` PHP config.

Can you set it and check again fresh installation?

**Comment by niemiha** [comment]
Ok, that seems to have made it. 

Sorry for the bother and not trying it myself, but as it is only warning I normally have got away with the missing timezone.

Thank you a lot for help

**Comment by corpsee** [comment]
@niemiha It's all right. I'm glad that I could help you.
