### ISSUE TITLE
Column "project_id" must be an integer.

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [php-censor/php-censor#164]
## Expected behavior

Clicking rebuild now starts a rebuild

## Actual behavior

Seeing error:

Sorry, there was a problem

`http://localhost.phpcensor/build/rebuild/3`
```
Message: Column "project_id" must be an integer.
File: php-censor/src/Model.php
Line: 102
Trace:
#0 php-censor/src/Model/Base/Build.php(109): PHPCensor\Model->validateInt('project_id', '1')
#1 php-censor/src/Service/BuildService.php(120): PHPCensor\Model\Base\Build->setProjectId('1')
#2 /php-censor/src/Controller/BuildController.php(253): PHPCensor\Service\BuildService->createDuplicateBuild(Object(PHPCensor\Model\Build\GitlabBuild))
#3 [internal function]: PHPCensor\Controller\BuildController->rebuild('3')
#4 /php-censor/src/Controller.php(63): call_user_func_array(Array, Array)
#5 /php-censor/src/WebController.php(86): PHPCensor\Controller->handleAction('rebuild', Array)
#6 /php-censor/src/Application.php(140): PHPCensor\WebController->handleAction('rebuild', Array)
#7 php-censor/src/Application.php(151): PHPCensor\Application->handleRequestInner()
#8 /php-censor/public/index.php(8): PHPCensor\Application->handleRequest()
#9 {main}
```
## Steps to reproduce

Click rebuild now

## Environment

* `master`
* Arch
* php 7.2
* MariaDB

**Comment by corpsee** [comment]
@Caffe1neAdd1ct Thank you! #166 Merged. +1
